#Saved on 1789214792623
#Sat Sep 12 13:06:32 BST 2026
LinEnum=/tmp/LinEnum/LinEnum.sh
ArpNames=-n
QuickLocalNetworkScan=-F $subnetMask -oX $xml
DetectAllServices=-T4 -sS -sU -p- -A $ip -oX $xml
DetectTCPServices=-T4 -sS -p- -A $ip -oX $xml
DetectUDPServices=-T4 -sU -p- -A $ip --top-ports 4096 --defeat-icmp-ratelimit -oX $xml
LoadKnownServices=false
ForceReScan=false
TargetTypeMappingFile=$resources/targets/target-type-mappings.csv
ExploitsCSVFileName=/usr/share/exploitdb/files_exploits.csv
ShellCodesCSVFileName=/usr/share/exploitdb/files_shellcodes.csv
CustomScriptsDirectory=$resources/scripts/custom
ExploitsDirectory=/usr/share/exploitdb/exploits
AWSS3BucketNamesWordList=$resources/wordlists/aws/s3-bucket-names.txt
Accept.Cookies.Search.Strings="text(Allow all cookies)", "text(Accept)","text(ACCEPT)","text(accept)","text(accept all)","text(I Accept)","text(Accept all)","aria-label(Close)"
AcronymsDirectory=$resources/keywords/acronyms
AdVerbsDirectory=$resources/keywords/adverbs
AddTargetScans=targets.csv
AdjectivesDirectory=$resources/keywords/adjectives
AmassEnumActive.command=amass enum -active -d $topLevelDomain -o $json -format json
AmassEnumActive.proxychains=true
AmassEnumPassive.command=amass enum -passive -d $topLevelDomain -o $json -format json -src
AmassEnumPassive.proxychains=true
AndroidUserAgentsFile=$resources/user-agent/android.txt
ApplicationTitle=T3T0
AtSameIpUrl=https\://intercode.info/webtools/atsameip/
BinPaths=/usr/bin/\:/home/kali/dev\:/home/kali/go
Black.Listed.Targets.File=$resources/targets/black-listed-targets.yaml
Browser.Highlight.Colour=red
Browser.Implicit.Timeout=20
Browser.Page.Load.Timeout=20
Browser.Script.Timeout=20\:q\!
BrowserName=firefox
BrowserProxy=tor
Brute.Force.Error.Locator=tag(pre),text(Username and/or password incorrect.)
Brute.Force.Password.Locator=tag(input),type(password),name(password)
Brute.Force.Submit.Locator=tag(input),type(submit),value(Login),name(Login)
Brute.Force.User.Name=admin
Brute.Force.User.Name.Locator=tag(input),type(text),name(username)
Brute.Force.User.Password=password
CPE.Master.Location=$resources/cpe/cpe-dictionary.xml
CPE.URL.Location=https\://nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml.gz
CVE.CSV.Master.File=$resources/cve/cve.csv
CVE.DownLoad.Location=C\:/Users/Shay/dev/cve/cves
CVE.Download.Location=c\:/Users/Shay/dev/cve
CVE.Records.Directory=/home/kali/IdeaProjects/gits/cvelistV5/cves
CVE.Repository.URI=https\://github.com/CVEProject/cvelistV5.git
Categories.File=$resources/keywords/categories/categories.csv
Categorize.File=$resources/keywords/categories/categorize.csv
Category.Mapping.File=$resources/keywords/categories/categories.csv
Cert.Alias=myob
Cert.Common.Name=Smith
Cert.Organization=Loosely coupled
Cert.Organization.Unit=10
Chrome.Executable.Path=/home/kali/IdeaProjects/fx10/src/main/resources/drivers/chromedriver-linux64/chromedriver
ChromeCachePath=C\:\\Users\\shay\\.cache\\selenium\\chromedriver\\win64\\144.0.7559.109\\chromedriver.exe
ChromeUserAgentsFile=$resources/user-agent/chrome.txt
Classify.Script.Records=false
Command.Injection.File=$resources/wordlists/command-injection/commands.txt
ConfigFileName=hack.properties
Cpe.Xml.File=$resources/cpe/official-cpe-dictionary_v2.3.xml
CrawlBrowser=firefox
CrawlDepth=6
CrawlMaxPages=20
CrawlUrlPatternMatchers=https\://,http\://
Create.CPE.Records=false
Create.CVE.Records=false
Create.Exploit.Records=false
Create.Known.Services.Records=false
Create.Regex.Records=false
Create.SearchSploit.Records=false
Create.Services=false
Create.Test.Data.File=$resources/targets/create-test-data.txt
Create.WhatWeb.Products=false
CreateTargetScans=true
CustomerName=BTC
CustomersMasterFile=$resources/services/customers/customers.yaml
DB.Create.Test.Data=true
DB.Drop.CPE=false
DB.Drop.CVE=false
DB.Drop.Exploit=false
DB.Drop.Table.ConfigurationItem=false
DB.Drop.Table.FXCustomer=false
DB.Drop.Table.FXDevice=false
DB.Drop.Table.FXProject=false
DB.Drop.Table.FXScan=false
DB.Drop.Table.FXScript=false
DB.Drop.Table.FXService=false
DB.Drop.Table.FXServiceNote=false
DB.Drop.Table.FXTarget=false
DB.Drop.Table.FXTargetNote=false
DB.Drop.Table.FXTargetTask=false
DB.Drop.Table.Provenance=false
DB.Drop.Table.Regex=false
DB.Drop.Tables=false
DB.Setup.Scripts.Directory=$resources/db/setup
DNS.Leak.Test.Url=https\://dnsleaktest.com/
DNS.Leak.Test.Url.Timeout=50000
DNSLeakTestUrlTimeout=500000
DVWA.Index.Page=http\://127.0.0.1/DVWA/index.php
DVWA.Login.Page=http\://127.0.0.1/DVWA/login.php
DVWA.Security.Page=http\://127.0.0.1/DVWA/security.php
Dalfox.command=dalfox url $url --waf-evasion --silence --no-color --fast-scan --format json -o $json
Dalfox.proxychains=true
DatabaseUrl=jdbc\:postgresql\://localhost/teto
DatabaseUserName=postgres
DatabaseUserPassword=R00tyT00ty
Default.Browser=TOR
DeleteScanData=false
DiscoveryLevel=0
DnsLeakTestUrl=https\://dnsleaktest.com/
DorksCSVFile=$resources/dorks/dorks.csv
DorksDirectory=$resources/dorks
DroolsDirectory=com/teto/hack/drools
DropScanDataTables=true
Duck.Duck.Go.Search=ddgs
DuckDuckGoUrl=https\://duckduckgo.com/html/?q\=
EcosiaUrl=https\://www.ecosia.org/search?method\=index&q\=
EdgeUserAgentsFile=$resources/user-agent/edge.txt
Enable.Scheduled.WebCrawls=false
Exploit.Exploits.CSV=/usr/share/exploitdb/files_exploits.csv
Exploit.Shell.Codes.CSV=/usr/share/exploitdb/files_shellcodes.csv
FX.Height=954.0
FX.Scene=FX.Scene.Main
FX.Theme=dracula
FX.Width=1853.0
FX.X=60.0
FX.Y=35.0
FXIconsFlagLocation=$resources/icons/flags
FXIconsLocation=$resources/icons
FXIconsMetaLocation=$resources/icons/meta
False.Positives.Directory=$resources/targets/false-positives
Fierce.command=fierce --domain $topLevelDomain
Fierce.proxychains=true
FireFox.Executable.Path=/home/kali/IdeaProjects/fx4/drivers/geckodriver-linux-64bit
FireFoxCachePath=C\:\\Users\\shay\\.cache\\selenium\\geckodriver\\win64\\0.36.0\\geckodriver.exe
Firefox.Executable.Path=/opt/geckodriver/geckodriver
FirefoxUserAgentsFile=$resources/user-agent/firefox.txt
Firewalk.command=nmap --script\=firewalk --traceroute --script-args\=firewalk.max-probed-ports\=-1 $ip -oX $xml
Firewalk.proxychains=true
FollowRedirects=true
ForceRerun=true
FormInputTags=text,button,password,submit
FuzzWordListDirectory=$resources/fuzzing
GDPR.Search.Patterns="aria-label(Close)"
Generate.Modules=false
GoBuster.command=gobuster dir --no-status --no-tls-validation --follow-redirects --url $url --wordlist $wordList --user-agent $userAgent --no-error --no-progress --quiet --thread $threads
GoBuster.proxychains=true
H8Mail.command=h8mail -t $source -j $json
H8Mail.proxychains=true
HTB.Url=https\://www.hackthebox.com/
HTB.User.Password=Energ\!zerMaxPlu2
HTB.UserName=shambells2@gmail.com
HeartBeat.Monitor.TimeOut=60000
Home=/home/kali/TETO
HttpRecon.command=nmap -sV $ip $ports --script\=httprecon-nse/httprecon.nse -oX $xml
HttpRecon.proxychains=true
IEUserAgentsFile=$resources/user-agent/ie.txt
Internet.Monitor.Timeout=60000
Ip.Address.Leakage.Continue=falsee
Katana=katana
Katana.command=katana -u $url -no-color -jsonl -td
Katana.proxychains=true
KeyWords.Phrase.Replace.Directory=$resources/keywords/phrases
KiteRunnerDirectory=$resources/scripts/kiterunner
Known.Services.File=$resources/services/known-services.csv
KnownOIDsFile=$resources/snmp/known_oids.csv
KnownServicesFile=$resources/services/known/known-services.csv
Language=en
Last.CPE.ID=653000
LoadBalance.command=lbd $domain
LoadBalance.proxychains=true
Login.Searches.Configuration=$resources/hacking/login-searches.csv
Main.Content.Split.Pane.Location=0.9291019581363943
Main.Split.Pane.Divider.Location=0.1958762886597938
MainScreenDefinition=$resources/fxml/Main.fxml
MaxExecutionDuration=3m
MaxExecutionTime=5
MaxResponseTime=5000
MaxThreads=100
Metasploit.DownLoad.Location=C\:/Users/Shay/dev/metasploit
Metasploit.Repository.URI=https\://github.com/rapid7/metasploit-framework.git
Mime3.Java.Code=/home/kali/IdeaProjects/fx4/src/main/java/com/teto/fx4/domain/mime/MimeType3.java
MinParallelism=100
MinWordLength=6
NMap.Executable.Path=nmap
New.Customer.Glyph.Name=PENCIL
NextUpdate=1755882362868
Nikto.command=nikto -Format xml -host $topLevelDomain -no404 -output $xml
Nikto.proxychains=false
NiktoRepository=/home/kali/dev/nitko
Nix.Command.Injection.File=$resources/wordlists/command-injection/nix.txt
Noisy.Tag.Words=$resources/keywords/noisy/noisy-tag-words.txt
Noisy.Words.File=$resources/keywords/noisy/noisy-words1.txt
Nuclei.command=nuclei -u $topLevelDomain -json-export $json
Nuclei.proxychains=true
NucleiConfigFile=$resources/nuclei/nuclei.csv
NucleiTemplateDirectory=/home/kali/.local/nuclei-templates
Nuke.Template.Directory=/home/kali/dev/nuclei-templates
Number.Of.Service.References.To.Display=25
OWASPpApiPath=/home/kali/IdeaProjects/www-project-api-security-testing-framework/target/api-security-testing-framework-1.0.0.jar
OperaUserAgentsFile=$resources/user-agent/opera.txt
Operating.System.Names.File=$resources/targets/os-names.csv
OutputDirectory=/home/kali/scans/$customer/$project/$target
Password.Searches.Configuration=$resources/hacking/password-searches.csv
Passwords.File=$resources/wordlists/passwords.txt
PasswordsFile=$resources/seclists/passwords/common_small.txt
Product.Names.Mapping.File=$resources/products/product-name-mappings.csv
Product.Replacement.File=$resources/cpe/cpe-product.csv
Project+LocalHost\ Project\ 1=true
Project.Glyph.Name=ARROW_CIRCLE_RIGHT
ProjectName=Project
ProjectsMasterFile=$resources/services/projects/projects.yaml
Proxy.Events.Of.Interest=HttpGet,HttpPost
Proxy.Port=8080
Python=$resources/scripts/python
Python.Base.Directory=$resources/python
RSS2.Schema.Location=$resources/xsd/rss/rss2.xsd
Regex.Yaml.File=$resources/regex/regex-searches.yml
RegexDirectory=$resources/secrets
RegexPatternsFile=$resources/regex/regex.properties
RegexPropertiesFile=$resources/regex/validated.properties
Replace.Words.File=$resources/keywords/replace/replace.csv
ResourcesDir=$resources
RunMode=UI
S3BucketNamesWordList=$resources/wordlists/aws/s3-bucket-names.txt
SafariUserAgentsFile=$resources/user-agent/safari.txt
Scan.Glyph.Name=CALENDAR
Scan.TASS.Discover=false
ScanAction=IngestScanData
ScanConfigDirectory=scans/$customer/$project/$target
ScanGranularity=dd-MM-YY
ScanPorts=1-63335
ScanStatus=PassiveScan
ScanTargets="BTC,"BTC Target",https\://btc.bw","TASS,"Tass Web",https\://tass.ru","Le Figaro,"Le Fig Web",https\://lefigaro.fr"
ScanType=addHoc
ScansToRun=all
Scene=runscripts
Scratch.Directory=/home/kali/TETO/scratch
Script.Update=$resources/scripts/update/update.sh
ScriptConfigDirectory=$resources/scripts
Scripts.Config.File=$resources/scripts/scripts.yaml
Scripts.Directory=$resources/scripts
Scripts.NSE.File=$resources/scripts/nse.csv
Scripts.Not.To.Run=spiderfoot,host-ns
ScriptsDirectory=$resources/scripts/specs
ScriptsMasterFile=$resources/services/scripts/scripts-master.yaml
ScriptsToRun=all
SearchSploit=searchsploit
SearchSploit.Alternative.Words.File=$resources/searchsploit/alternatives.csv
SearchSploit.Download.Location=c\:/Users/Shay/dev/exploitdb
SearchSploit.Git.URI=https\://gitlab.com/exploit-database/exploitdb.git
SearchSploit.Redundant.Words.File=$resources/searchsploit/redundant-words.csv
SearchSploit.command=searchsploit $searchSploit --disable-color -j
SearchSploit.proxychains=\=false
SecListDirectory=/usr/share/seclists
SecListsFile=$resources/seclists/SecLists.yaml
Secrets.Patterns.DB=/home/kali/IdeaProjects/gits/secrets-patterns-db
Secrets.Scanning.Custom.Patterns=$resources/gits/secret-scanning-custom-patterns
Sherlock.command=sherlock $userName --verbose --csv --print-found --no-color -o $csv
Sherlock.proxychains=true
ShowGridPaneLines=false
SourceCodeRootDirectory=$java
SpiderFoot.Modules.Use.Case=investigate
SplitPaneDividerLocation.0=0.2334448160535117
SplitPaneDividerLocation.1=0.7678929765886288
SpoofMacAddress=false
StageHeight=832.0
StageWidth=1505.0
StageXPos=215.0
StageYPos=35.0
Stages=20
StagesToComplete=20
StatusCodesOfInterest=100-402,404-500
StatusMinimumLevelReporting=0
Steps=-1
StepsToComplete=-1
String.Caps.File=$resources/names/string-caps.csv
SupportedLanguages=en,fr,de,es
SynonymsFile=$resources/keywords/synonyms/Synonyms.csv
TFTPWordList=$resources/wordlists/tftp/tftp.txt
TOR.Profile=/home/kali/.local/share/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/profile.default
TOR.Proxy.List.Url=https\://api.proxyscrape.com/v4/free-proxy-list/get?request\=display_proxies&proxy_format\=protocolipport&format\=text
TOR.Start.Script=/bin/torbrowser-launcher
TagIconsPropertiesFile=$resources/icons/TagIcons.properties
Target.GDPR.FileName=$resources/gdpr/target_gdpr_locators.csv
Target.Glyph.Name=DEVIANTART
Target.Rules.Path=$resources/com/teto/fx4/domain/target
Target.Software.Replacement.File=$resources/cpe/cpe-targetsw.csv
TargetDisplayDefinition=$resources/fxml/TargetDisplay.fxml
TargetName=Target
TargetTypeRegexDirectory=$resources/regex/target-types
TargetUri=https\://btc.bw
TargetsFile=$resources/targets/targets.yaml
TargetsMasterFile=$resources/services/targets/targets.yaml
TcpScanPorts=-p0-
Technology.Directory=/home/kali/dev/webappanalyzer/src/technologies
TempDirectory=/tmp
Theme=Theme.dracula
Threads=200
ToolBar.Button.Style=-fx-border-color\: darkgray; -fx-border-width\: 1px; -fx-border-radius\: 8px;
Tor.Proxy.Host=127.0.0.1
Tor.Proxy.Port.Number=9050
Translation.Bundle.Directory=$resources
TruncateScanTables=true
URL.Rules.Path=$resources/rules/com/teto/command/targets/flow
UdpScanPorts=-p0-
Unknown.Glyph.Name=QUESTION
Update.CPE.Dictionary=false
Update.Days.Interval=31
Update.External.Data.Override=true
Update.Master.Script=$resources/update/update.sh
UpdateScriptCounts=true
UrlFuzzingWordList=
UrlStartsWithPatterns=https\://,http\://
Urls.Definition.File=$resources/urls
UseCase=all
UserAgent=random
UserName.Searches.Configuration=$resources/hacking/user-name-searches.csv
UserNamesFile=$resources/seclists/usernames/common.txt
VariableNamesReplaceFile=$resources/java/variable-names.csv
Vendor.Replacement.File=$resources/cpe/cpe-vendor.csv
VerbsDirectory=$resources/keywords/verbs
VirtualHostsWordList=$resources/wordlists/vhosts/virtual-host-wordlist.txt
Vulscan.command=nmap $ip $ports --script\=vulscan/vulscan.nse -oX $xml
Vulscan.proxychains=true
WafDetect.command=nmap $ip --script\=http-waf-detect -oX $xml
WafDetect.proxychains=true
WafDetectorBuildCommand=cargo build --release
WafDetectorRepository=/home/kali/dev/waf-detector
WafFingerPrint.command=nmap $ip --script\=http-waf-fingerprint -oX $xml
WafFingerPrint.proxychains=true
WafW00f.command=wafw00f --no-colors $url
WafW00f.proxychains=true
Wappalyzer.command=node /home/kali/IdeaProjects/wappalyzer/src/drivers/npm/cli.js $url
Wappalyzer.proxychains=false
WebPage.Glyph.Name=BOOKMARK
WebSite.Glyph.Name=SITEMAP
WebTech.command=webtech -u $url --json > $json
WebTech.proxychains=false
WebTechnologyScripts=WhatWeb,WebTech,WafW00f
WhatWeb.Location=C\:/Users/Shay/dev/WhatWeb/whatweb
WhatWeb.Products.Directory=$resources/products
WhatWeb.Products.File=$resources/products/whatweb-identifiable-products
WhatWeb.command=whatweb -a 1 --color\=never --no-errors $topLevelDomain --log-xml\=$xml
WhatWeb.proxychains=true
Windows.Command.Injection.File=$resources/wordlists/command-injection/windows.txt
WordListsDirectory=/usr/share/wordlists
Zap.Api=5tlc1ceul7bked523pe9up612r
Zap.Executable.Path=zaproxy -addoninstallall
Zap.Host=localhost
Zap.Port=8080
ZapApiKey=1234
ZapProxyHost=127.0.0.1
ZapProxyPort=9080
crawl.command=katana -u $url -iqp -match-regex $mainSiteUrl -crawl-duration $maxExecutionDuration -pc -kf robotstxt -c 10 -delay 3 -no-color -o $txt
crawl.proxychains=true
createNucleiConfiguration=false
discoveryLevel=0
osDetection=true
passiveScripts=HttpRecon,WhatWeb,WebTech,WafW00f
quitIfIPAddressIsLeaking=false
scriptOutputDirectory=$targetLocation
serviceVersionDetection=true
synscan.command=nmap --traceroute $ip -sS -Pn -oX $xml
theHarvester.Api.End.Points=$resources/scripts/theHarvester/api_endpoints.txt
theHarvester.command=theHarvester -d $topLevelDomain -t -q -b all -f $json
theHarvester.proxychains=false
