package com.teto.domain.provenance;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public enum Provenance {
    // $Tag
    DnsEnum(-1),
    KiteRunnerListWordLists(-1),
    AutoRecon(-1),
    DnsRecon(-1),
    Dalfox(-1),

    WafDetect(0),
    QconnExec("qconn-exec", 1),
    DetectOs(1),
    ReconFTWPassive(2),
    QuickLocalNetworkScan(1),
    SubFinder(2),
    DetectUDPServices(-1),
    DetectAllServices(2),
    HPing3AllTCPPorts(-1),
    HPing3AllUDPPorts(3),
    HttpRecon(3),
    HttpWafDetect(4),
    ReconFTWActive(4),
    WafFingerPrint(5),

    WebTech(5),
    WafW00f(5),
    SpringBoot(-1),
    VerifyTarget(6),
    HttpUseragentTester("http-useragent-tester", 7),
    AssetFinder(10),
    NbtScan(10),
    KiteRunnerApiScan(10),
    KiteRunnerLargeApiScan(10),
    KiteRunnerSmallApiScan(10),
    OWASPApi(10),
    NMapSamba(10),
    NMapLDAP(10),
    NMapNFS(10),
    NMapVuln(10),
    NMapSNMP(10),
    NMapFTP(10),
    Vulscan(10),
    SNMPWalk(20),
    LoadBalance("lbd", 10),
    PgsqlBrute("pgsql-brute", 10),

    RunExploits,
    theHarvester("theHarvester", 15),
    FFUFDirectoryScan(20),
    AggressiveNMap(20),

    CrackTelnet(50),
    CrackHttp(50),
    CrackHttps(50),
    CrackWordPress(50),
    CrackJoomla(50),
    CrackDicom(50),
    CrackPOP3(50),
    CrackIMAP(50),
    CrackNETBIOS(50),
    CrackSAMBA(50),
    CrackOWA(50),
    CrackSIP(50),
    CrackMSSQL(50),
    CrackPSQL(50),
    CrackVNC(50),
    CrackRDP(50),
    CrackMYSQL(50),
    CrackRedis(50),
    CrackWinRM(50),
    CrackCassandra(50),
    CrackMongoDB(50),
    CrackCVS(50),

    SSHAudit(100),
    ArjunGet(100),
    ArjunPost(100),
    BroadcastBjnpDiscover("broadcast-bjnp-discover", 100),

    CurlOpenPorts(200),
    RdpNtlmInfo("rdp-ntlm-info", 201),
    HttpSlowlorisCheck("http-slowloris-check",202),
    HttpVulnCve20175689("http-vuln-cve2017-5689", 203),
    HttpSlowloris("http-slowloris", 204),
    Asn(205),
    BadRequest(206),
    IdentifySNMPCommunityStrings(207),
    CrawlWebSite,
    XMasScan(208),
    NullScan(209),
    FINScan(210),
    SearchSploit,
    SearchSploitNMAP,
    SearchSploitKeyTerms,
    MaimonScan(211),
    WindowScan(212),
    ZombieScan(213),
    Firewalk("firewalk", 214),
    Wapiti(215),
    GraphW00f(216),
    HydraSSH(250),
    HydraFTP(250),

    SIPMap(300),
    AtSameIP(303),
    BannerGrab(304),
    SIPWar(400),
    SIPCrack(401),
    CPanel(402),
    DnsMap(403),
    SIPReport(404),
    Fierce(406),
    SIPCrash(409),

    Maigret(500),
    GoBusterDir(10),
    GoBusterDNS(501),
    GoBusterFuzz(501),
    GoBusterTFtp(501),
    GoBusterS3(501),
    GoBusterGCS(501),
    GoBusterVHosts(501),
    GoSpider(502),
    SSLScan(503),
    SNMPSystemName(504),
    Dirb(506),
    SNMPSystemDescription(507),
    SNMPInterfaceDescriptions(508),
    Nuclei(509),
    SNMPAddressesOnInterfaces(511),
    SNMPArpTableIP2MAC(512),
    Sherlock(513),
    SqlMap(514),
    SNMPRunningPrograms(515),
    SNMPInstalledSoftware(516),
    SNMPWindowsStorageDescriptions(518),
    SNMPSystemLoad(519),

    HttpOpenProxy("http-open-proxy", 250),
    NMapBanner("banner", 350),

    DirBuster,

    LocateWebForms,
    LocateLoginWebForms,
    ProbeWebSite,
    Wappalyzer,
    SpiderFootDomain,
    GrafW00f,
    Nikto,
    MassScan,
    SkipFish,
    OSRFUser,
    OSRFDomain,
    OSRFEMail,
    OSRFSearch,
    OSRFPhone,
    DetectPacketForgeryByFirewall,
    DetectPacketForgeryByIDS,

    AsnLookUp,
    AsnDomain,WhatWeb,Sublist3r,

    Katana,
    Crawl,
    H8Mail,

    IdentifyOperatingSystem,
    IdentifyTargetByUrl,

    Dmitry,
    NSLookup,
    WhoIs,
    SpiderFoot,
    DuckDuckGo,
    ClearLogs,
    UninstallApps,
    DeleteFiles,
    DeleteDirectories,
    CreateDirectory,
    CreateFile,
    InstallApp,
    PrioritizeTargets,
    DetectTCPServices(2),
    SocialSearcher,
    DeviceDiscovery,
    AssetDiscovery,
    PhysicalMapping,
    LogicalMapping,
    Connectivity,
    Configuration,
    Settings,
    SNMP,
    Security,
    Firewall,
    CDL,
    LLDP,
    Hybrid,
    LDAP,
    NFS,
    POP4,
    FTP,
    Samba,
    REST,
    SOAP,
    WebSocket,
    Email,
    SMS,
    Social,
    MaliciousLinks,
    MaliciousAttachments,
    SensitiveInformation,
    SpearPhishing,
    Phishing,
    MassAttacks,
    SynScan,SynScanBadCheckSum,
    IPProtocolScan,
    AckScan,
    ConnectScan,
    CookieEchoScan,
    FTPBounceScan,
    ListScan,
    PingScan,
    ProtocolScan,
    ServiceVersionScan,
    AmassEnum,
    AmassEnumBrute,
    HydraFtp,
    Cewl,

    CommandLineArguments,
    NMap,
    GetAllUrls,

    ScillaDNS,
    ScillaPort,
    ScillaSubDomain,
    ScillaDirectory,

    DiscoverHiddenParameters,
    BigBosintSubDomain,
    GoDork,

    FaviRecon,
    ContentSecurityPolicyRecon,
    ManyPaths4ManyHosts,
    PureDNS,
    HakCrawler,
    NaaBu,
    WordPressScan,
    Uncover,
    ASNMap,
    AttackSurfaceMapper,
    JWTHack,
    DavTest,
    FeroxBuster,
    DNSRecon,
    Dig,
    FFuF,
    SubList3r,
    WFuzz,
    WIFIProtectedSetupScan,
    WebApplicationScannerSkipFish,
    ASNLookup,
    NmMap,
    TraceRoute,
    RemoveUnknownTargets,
    RemoveInvalidDomains,

    ConvertDomainsToIpAddresses,
    VerifyTargetsAlive,

    NetworkMaps,NetworkBlocks,IPAddresses,Ports,OperatingSystems,Services,DNSConfiguration,AliveMachines,Systems,Repositories,Technologies,

    WebPresence,PhysicalLocations,Employees,Departments,
    Emails,Partners,ThirdParties,Press,NewReleases,
    Documents,JobPostings,

    MikrotikRouterosUsernameBrute("mikrotik-routeros-username-brute"),
    SmbEnumServices("smb-enum-services"),
    HttpRobotsTxt("http-robots.txt"),
    BroadcastSonicwallDiscover("broadcast-sonicwall-discover"),
    SnmpBrute("snmp-brute"),
    HttpVulnCve20142127("http-vuln-cve2014-2127"),
    MikrotikRouterosBrute("mikrotik-routeros-brute"),
    HttpVulnCve20175638("http-vuln-cve2017-5638"),
    HttpVhosts("http-vhosts"),
    Ipv6NodeInfo("ipv6-node-info"),
    EpmdInfo("epmd-info"),
    SnmpHh3cLogins("snmp-hh3c-logins"),
    CassandraBrute("cassandra-brute"),
    MemcachedInfo("memcached-info"),
    BroadcastDhcp6Discover("broadcast-dhcp6-discover"),
    IscsiInfo("iscsi-info"),
    ModbusDiscover("modbus-discover"),
    MmouseExec("mmouse-exec"),
    MetasploitMsgrpcBrute("metasploit-msgrpc-brute"),
    LdapSearch("ldap-search"),
    ImapCapabilities("imap-capabilities"),
    CicsUserEnum("cics-user-enum"),
    NetbusInfo("netbus-info"),
    BroadcastXdmcpDiscover("broadcast-xdmcp-discover"),
    SslDhParams("ssl-dh-params"),
    OpenwebnetDiscovery("openwebnet-discovery"),
    TorConsensusChecker("tor-consensus-checker"),
    HttpCsrf("http-csrf"),
    MysqlVariables("mysql-variables"),
    SmbVulnMs10061("smb-vuln-ms10-061"),
    HttpRefererChecker("http-referer-checker"),
    FtpSyst("ftp-syst",5),
    HadoopTasktrackerInfo("hadoop-tasktracker-info"),
    Db2DasInfo("db2-das-info"),
    LdapRootdse("ldap-rootdse"),
    MsSqlTables("ms-sql-tables"),
    UpnpInfo("upnp-info"),
    HttpGoogleMalware("http-google-malware"),
    TelnetEncryption("telnet-encryption"),
    BitcoinrpcInfo("bitcoinrpc-info"),
    NbdInfo("nbd-info"),
    HttpDrupalEnum("http-drupal-enum"),
    SmtpBrute("smtp-brute"),
    Duplicates("duplicates"),
    HttpCookieFlags("http-cookie-flags"),
    HttpHpIloInfo("http-hp-ilo-info"),
    LlmnrResolve("llmnr-resolve"),
    MsrpcEnum("msrpc-enum"),
    LdapBrute("ldap-brute"),
    MurmurVersion("murmur-version"),
    SocksAuthInfo("socks-auth-info"),
    DrdaBrute("drda-brute"),
    FirewallBypass("firewall-bypass", 2),
    Pop3Brute("pop3-brute"),
    CvsBrute("cvs-brute"),
    HttpFavicon("http-favicon"),
    HttpMobileversionChecker("http-mobileversion-checker"),
    HttpQnapNasInfo("http-qnap-nas-info"),
    CvsBruteRepository("cvs-brute-repository"),
    HttpShellshock("http-shellshock"),
    CitrixEnumApps("citrix-enum-apps"),
    DnsClientSubnetScan("dns-client-subnet-scan"),
    HttpDevframework("http-devframework"),
    MongodbDatabases("mongodb-databases"),
    NatPmpMapport("nat-pmp-mapport"),
    SslCcsInjection("ssl-ccs-injection"),
    HostmapCrtsh("hostmap-crtsh"),
    HttpErrors("http-errors"),
    InformixQuery("informix-query"),
    MsSqlQuery("ms-sql-query"),
    Fcrdns("fcrdns"),
    DnsBlacklist("dns-blacklist"),
    HttpVirustotal("http-virustotal"),
    NntpNtlmInfo("nntp-ntlm-info"),
    HttpVulnWnr1000Creds("http-vuln-wnr1000-creds"),
    MaxdbInfo("maxdb-info"),
    BroadcastHidDiscoveryd("broadcast-hid-discoveryd"),
    BroadcastNovellLocate("broadcast-novell-locate"),
    JdwpExec("jdwp-exec"),
    AjpMethods("ajp-methods"),
    SslKnownKey("ssl-known-key"),
    CitrixEnumServers("citrix-enum-servers"),
    BroadcastListener("broadcast-listener"),
    IpmiBrute("ipmi-brute"),
    SmbServerStats("smb-server-stats"),
    AuthSpoof("auth-spoof"),
    CicsInfo("cics-info"),
    MsSqlDumpHashes("ms-sql-dump-hashes"),
    NjePassBrute("nje-pass-brute"),
    BittorrentDiscovery("bittorrent-discovery"),
    HttpAuthFinder("http-auth-finder"),
    SmtpEnumUsers("smtp-enum-users"),
    SmbEnumDomains("smb-enum-domains"),
    SslEnumCiphers("ssl-enum-ciphers"),
    BitcoinInfo("bitcoin-info"),
    RtspUrlBrute("rtsp-url-brute"),
    RsyncBrute("rsync-brute"),
    RdpEnumEncryption("rdp-enum-encryption"),
    SmbVulnWebexec("smb-vuln-webexec"),
    AuthOwners("auth-owners"),
    CitrixEnumAppsXml("citrix-enum-apps-xml"),
    StunInfo("stun-info"),
    Smb2SecurityMode("smb2-security-mode"),
    HttpHeaders("http-headers"),
    DnsRecursion("dns-recursion"),
    HttpWordpressEnum("http-wordpress-enum"),
    IpForwarding("ip-forwarding"),
    BroadcastUpnpInfo("broadcast-upnp-info"),
    HttpSapNetweaverLeak("http-sap-netweaver-leak"),
    SvnBrute("svn-brute"),
    SslHeartbleed("ssl-heartbleed"),
    HadoopJobtrackerInfo("hadoop-jobtracker-info"),
    AcarsdInfo("acarsd-info"),
    RpcGrind("rpc-grind"),
    RsyncListModules("rsync-list-modules"),
    VentriloInfo("ventrilo-info"),
    SmbBrute("smb-brute"),
    TftpVersion("tftp-version"),
    Omp2EnumTargets("omp2-enum-targets"),
    HttpMethods("http-methods"),

    RmiVulnClassloader("rmi-vuln-classloader"),
    AllseeingeyeInfo("allseeingeye-info"),
    BroadcastSybaseAsaDiscover("broadcast-sybase-asa-discover"),
    HttpVulnCve20063392("http-vuln-cve2006-3392"),
    BroadcastEigrpDiscovery("broadcast-eigrp-discovery"),
    IpmiVersion("ipmi-version"),
    HttpVulnCve20178917("http-vuln-cve2017-8917"),
    InformixTables("informix-tables"),
    SmbEnumSessions("smb-enum-sessions"),
    PortStates("port-states"),
    HttpInternalIpDisclosure("http-internal-ip-disclosure"),
    SmtpNtlmInfo("smtp-ntlm-info"),
    MysqlUsers("mysql-users"),
    LdapNovellGetpass("ldap-novell-getpass"),
    HttpJoomlaBrute("http-joomla-brute"),
    IrcUnrealircdBackdoor("irc-unrealircd-backdoor"),
    Tn3270Screen("tn3270-screen"),
    HadoopSecondaryNamenodeInfo("hadoop-secondary-namenode-info"),
    RexecBrute("rexec-brute"),
    HttpUserdirEnum("http-userdir-enum"),
    MysqlVulnCve20122122("mysql-vuln-cve2012-2122"),
    EnipInfo("enip-info"),
    HttpRobtexReverseIp("http-robtex-reverse-ip"),
    GopherLs("gopher-ls"),
    TargetsIpv6MulticastInvalidDst("targets-ipv6-multicast-invalid-dst"),
    X11Access("x11-access"),
    AjpHeaders("ajp-headers"),
    NjeNodeBrute("nje-node-brute"),
    Iax2Version("iax2-version"),
    SmtpOpenRelay("smtp-open-relay"),
    XdmcpDiscover("xdmcp-discover"),
    HttpCrossDomainPolicy("http-cross-domain-policy", 100),
    McafeeEpoAgent("mcafee-epo-agent"),
    HttpXssed("http-xssed"),
    SmbVulnRegsvcDos("smb-vuln-regsvc-dos"),
    SnmpInterfaces("snmp-interfaces"),
    HttpLitespeedSourcecodeDownload("http-litespeed-sourcecode-download"),
    RloginBrute("rlogin-brute"),
    HttpIcloudSendmsg("http-icloud-sendmsg"),
    FtpAnon("ftp-anon"),
    VersantInfo("versant-info"),
    MikrotikRouterosVersion("mikrotik-routeros-version"),
    NcpEnumUsers("ncp-enum-users"),
    SmbEnumGroups("smb-enum-groups"),
    SmbPsexec("smb-psexec"),
    NtpMonlist("ntp-monlist"),
    CitrixEnumServersXml("citrix-enum-servers-xml"),
    TsoBrute("tso-brute"),
    HddtempInfo("hddtemp-info"),
    RsaVulnRoca("rsa-vuln-roca"),
    SmtpVulnCve20104344("smtp-vuln-cve2010-4344"),
    BroadcastWakeOnLan("broadcast-wake-on-lan"),
    ProfinetCmLookup("profinet-cm-lookup"),
    BroadcastTellstickDiscover("broadcast-tellstick-discover"),
    BroadcastRipngDiscover("broadcast-ripng-discover"),
    DnsUpdate("dns-update"),
    BroadcastVersantLocate("broadcast-versant-locate"),
    HttpNtlmInfo("http-ntlm-info"),
    SslCert("ssl-cert"),
    HttpVulnCve20142128("http-vuln-cve2014-2128"),
    VncTitle("vnc-title"),
    HttpTraceroute("http-traceroute"),
    WeblogicT3Info("weblogic-t3-info"),
    HttpVulnCve20130156("http-vuln-cve2013-0156"),
    Iax2Brute("iax2-brute"),
    DistccCve20042687("distcc-cve2004-2687"),
    SmtpVulnCve20111764("smtp-vuln-cve2011-1764"),
    HttpMajordomo2DirTraversal("http-majordomo2-dir-traversal"),
    HttpSecurityHeaders("http-security-headers"),
    SshAuthMethods("ssh-auth-methods"),
    BroadcastJenkinsDiscover("broadcast-jenkins-discover"),
    BroadcastMsSqlDiscover("broadcast-ms-sql-discover"),
    BroadcastRipDiscover("broadcast-rip-discover"),
    TelnetBrute("telnet-brute"),
    OvsAgentVersion("ovs-agent-version"),
    BroadcastDb2Discover("broadcast-db2-discover"),
    SupermicroIpmiConf("supermicro-ipmi-conf"),
    DictInfo("dict-info"),
    HttpSitemapGenerator("http-sitemap-generator"),
    CccamVersion("cccam-version"),
    TlsNextprotoneg("tls-nextprotoneg"),
    NpingBrute("nping-brute"),
    SipEnumUsers("sip-enum-users"),
    MsSqlInfo("ms-sql-info"),
    NrpeEnum("nrpe-enum"),
    MulticastProfinetDiscovery("multicast-profinet-discovery"),
    SnmpSysdescr("snmp-sysdescr"),
    PuppetNaivesigning("puppet-naivesigning"),
    SmbVulnCve20093103("smb-vuln-cve2009-3103"),
    HttpTrace("http-trace"),
    SnmpWin32Shares("snmp-win32-shares"),
    DnsCheckZone("dns-check-zone"),
    VmwareVersion("vmware-version"),
    HttpVulnCve20093960("http-vuln-cve2009-3960"),
    CupsInfo("cups-info"),
    HttpAxis2DirTraversal("http-axis2-dir-traversal"),
    FoxInfo("fox-info"),
    HttpVulnCve20151635("http-vuln-cve2015-1635"),
    HttpFrontpageLogin("http-frontpage-login"),
    SipMethods("sip-methods"),
    HttpCommentsDisplayer("http-comments-displayer"),
    Daytime("daytime"),
    HttpTraneInfo("http-trane-info"),
    DelugeRpcBrute("deluge-rpc-brute"),
    TargetsXml("targets-xml"),
    VtamEnum("vtam-enum"),
    BroadcastPing("broadcast-ping"),
    HbaseRegionInfo("hbase-region-info"),
    IrcBrute("irc-brute"),
    HostmapBfk("hostmap-bfk", 100),

    BroadcastNetworkerDiscover("broadcast-networker-discover"),
    Ipv6RaFlood("ipv6-ra-flood"),
    CredsSummary("creds-summary"),
    HttpDrupalEnumUsers("http-drupal-enum-users"),
    HttpPhpVersion("http-php-version"),
    FtpVulnCve20104221("ftp-vuln-cve2010-4221"),
    Ssh2EnumAlgos("ssh2-enum-algos"),
    FreelancerInfo("freelancer-info"),
    HttpDlinkBackdoor("http-dlink-backdoor"),
    TargetsIpv6MulticastMld("targets-ipv6-multicast-mld"),
    IsnsInfo("isns-info"),
    HttpFormBrute("http-form-brute"),
    BitcoinGetaddr("bitcoin-getaddr"),
    HttpSqlInjection("http-sql-injection"),
    WhoisIp("whois-ip"),
    BroadcastWsddDiscover("broadcast-wsdd-discover"),
    MsSqlDac("ms-sql-dac"),
    JdwpVersion("jdwp-version"),
    MysqlEmptyPassword("mysql-empty-password"),
    BroadcastAvahiDos("broadcast-avahi-dos"),
    SmbDoublePulsarBackdoor("smb-double-pulsar-backdoor"),
    HbaseMasterInfo("hbase-master-info"),
    ImapBrute("imap-brute"),
    CupsQueueInfo("cups-queue-info"),
    DominoEnumUsers("domino-enum-users"),
    SnmpNetstat("snmp-netstat"),
    HttpFormFuzzer("http-form-fuzzer"),
    CitrixBruteXml("citrix-brute-xml"),
    HttpProxyBrute("http-proxy-brute", 250),
    Iec61850Mms("iec61850-mms"),
    HttpAwstatstotalsExec("http-awstatstotals-exec"),
    MsSqlXpCmdshell("ms-sql-xp-cmdshell"),
    NtpInfo("ntp-info"),
    SmbOsDiscovery("smb-os-discovery"),
    BroadcastDropboxListener("broadcast-dropbox-listener"),
    HttpUnsafeOutputEscaping("http-unsafe-output-escaping"),
    TargetsAsn("targets-asn"),
    CassandraInfo("cassandra-info"),
    RtspMethods("rtsp-methods"),
    IpGeolocationIpinfodb("ip-geolocation-ipinfodb"),
    TlsAlpn("tls-alpn"),
    DomconCmd("domcon-cmd"),
    NfsShowmount("nfs-showmount"),
    MysqlEnum("mysql-enum"),
    NetbusVersion("netbus-version"),
    SmbVulnMs06025("smb-vuln-ms06-025"),
    GangliaInfo("ganglia-info"),
    HttpPhpselfXss("http-phpself-xss"),
    SmbEnumShares("smb-enum-shares"),

    PjlReadyMessage("pjl-ready-message"),
    ShodanApi("shodan-api"),
    SocksOpenProxy("socks-open-proxy"),
    HttpVulnCve20171001000("http-vuln-cve2017-1001000"),
    FtpLibopie("ftp-libopie"),
    CoapResources("coap-resources"),
    NatPmpInfo("nat-pmp-info"),
    RedisInfo("redis-info"),
    SmbVulnConficker("smb-vuln-conficker"),
    StunVersion("stun-version"),
    HttpBrute("http-brute"),
    MembaseBrute("membase-brute"),
    BjnpDiscover("bjnp-discover"),
    PcworxInfo("pcworx-info"),
    SmbVulnMs08067("smb-vuln-ms08-067"),
    SipBrute("sip-brute"),
    SnmpWin32Services("snmp-win32-services"),
    HttpGrep("http-grep"),
    HttpVulnCve20137091("http-vuln-cve2013-7091"),
    HttpWordpressBrute("http-wordpress-brute"),
    WdbVersion("wdb-version"),
    TargetsTraceroute("targets-traceroute"),
    FtpProftpdBackdoor("ftp-proftpd-backdoor"),
    Ipidseq("ipidseq"),
    DnsBrute("dns-brute"),
    MsSqlHasdbaccess("ms-sql-hasdbaccess"),
    MsSqlNtlmInfo("ms-sql-ntlm-info"),
    OracleSidBrute("oracle-sid-brute"),
    HttpSvnInfo("http-svn-info"),
    PptpVersion("pptp-version"),
    AmqpInfo("amqp-info"),
    FtpBrute("ftp-brute"),
    BroadcastPimDiscovery("broadcast-pim-discovery"),
    DnsSrvEnum("dns-srv-enum"),
    MmouseBrute("mmouse-brute"),
    TlsTicketbleed("tls-ticketbleed"),
    DnsCacheSnoop("dns-cache-snoop"),
    Pop3Capabilities("pop3-capabilities"),
    Vulners("vulners"),

    Quake1Info("quake1-info"),
    HttpColdfusionSubzero("http-coldfusion-subzero"),
    TargetsIpv6MulticastSlaac("targets-ipv6-multicast-slaac"),
    BackorificeInfo("backorifice-info"),
    MysqlDatabases("mysql-databases"),
    Smb2Capabilities("smb2-capabilities"),
    SmtpVulnCve20111720("smtp-vuln-cve2011-1720"),
    BroadcastAtaoeDiscover("broadcast-ataoe-discover"),
    Rpcinfo("rpcinfo"),
    AjpRequest("ajp-request"),
    Quake3Info("quake3-info"),
    NbnsInterfaces("nbns-interfaces"),
    SmbLs("smb-ls"),
    MsSqlBrute("ms-sql-brute"),
    TracerouteGeolocation("traceroute-geolocation"),
    SambaVulnCve20121182("samba-vuln-cve-2012-1182"),
    SmbProtocols("smb-protocols"),
    KnxGatewayInfo("knx-gateway-info"),
    DnsFuzz("dns-fuzz"),
    JdwpInfo("jdwp-info"),
    DhcpDiscover("dhcp-discover"),
    SmbEnumUsers("smb-enum-users"),
    HttpBigipCookie("http-bigip-cookie"),
    HttpVulnCve20136786("http-vuln-cve2013-6786"),
    MysqlAudit("mysql-audit"),
    Sslv2("sslv2"),
    HttpCors("http-cors"),
    SmbVulnMs07029("smb-vuln-ms07-029"),
    AddressInfo("address-info"),
    VmauthdBrute("vmauthd-brute"),
    BacnetInfo("bacnet-info"),
    BroadcastPcAnywhere("broadcast-pc-anywhere"),
    SslCertIntaddr("ssl-cert-intaddr"),
    GkrellmInfo("gkrellm-info"),
    HttpHuaweiHg5xxVuln("http-huawei-hg5xx-vuln"),
    VuzeDhtInfo("vuze-dht-info"),
    Servicetags("servicetags"),
    SmbFlood("smb-flood"),
    UnusualPort("unusual-port"),
    VoldemortInfo("voldemort-info"),
    NetbusAuthBypass("netbus-auth-bypass"),
    HttpIcloudFindmyiphone("http-icloud-findmyiphone"),
    HttpVulnCve20151427("http-vuln-cve2015-1427"),
    HttpMalwareHost("http-malware-host"),
    IpGeolocationMaxmind("ip-geolocation-maxmind"),
    JdwpInject("jdwp-inject"),
    NdmpFsInfo("ndmp-fs-info"),
    BroadcastIgmpDiscovery("broadcast-igmp-discovery"),
    Mtrace("mtrace"),
    TelnetNtlmInfo("telnet-ntlm-info"),
    HttpWafFingerprint("http-waf-fingerprint"),
    CouchdbStats("couchdb-stats"),
    SmbWebexecExploit("smb-webexec-exploit"),
    HttpDefaultAccounts("http-default-accounts"),
    HttpCakephpVersion("http-cakephp-version"),
    MysqlInfo("mysql-info"),
    PcanywhereBrute("pcanywhere-brute"),
    HttpVulnCve20142129("http-vuln-cve2014-2129"),
    Pop3NtlmInfo("pop3-ntlm-info"),
    AsnQuery("asn-query"),
    ClamavExec("clamav-exec"),
    SmbMbenum("smb-mbenum"),
    MysqlBrute("mysql-brute"),
    SshRun("ssh-run"),
    SshPublickeyAcceptance("ssh-publickey-acceptance"),
    AjpAuth("ajp-auth"),
    IpGeolocationGeoplugin("ip-geolocation-geoplugin"),
    DnsRandomSrcport("dns-random-srcport"),
    GpsdInfo("gpsd-info"),
    SnmpIosConfig("snmp-ios-config"),
    Smb2VulnUptime("smb2-vuln-uptime"),
    ClockSkew("clock-skew"),
    HttpGit("http-git"),
    RiakHttpInfo("riak-http-info"),
    HttpIisShortNameBrute("http-iis-short-name-brute"),
    DnsRandomTxid("dns-random-txid"),
    HttpCiscoAnyconnect("http-cisco-anyconnect"),
    HttpFetch("http-fetch"),
    HttpExifSpider("http-exif-spider"),
    DnsServiceDiscovery("dns-service-discovery"),
    IecIdentify("iec-identify"),
    SshHostkey("ssh-hostkey"),
    SipCallSpoof("sip-call-spoof"),
    HttpVmwarePathVuln("http-vmware-path-vuln"),
    HttpVulnCve20100738("http-vuln-cve2010-0738"),
    IcapInfo("icap-info"),
    Smb2Time("smb2-time"),
    DnsNsecEnum("dns-nsec-enum"),
    HttpsRedirect("https-redirect"),
    OpenflowInfo("openflow-info"),
    Sslv2Drown("sslv2-drown"),
    IkeVersion("ike-version"),
    SmbVulnMs10054("smb-vuln-ms10-054"),
    HttpPasswd("http-passwd"),
    IrcBotnetChannels("irc-botnet-channels"),
    XmppBrute("xmpp-brute"),
    MongodbBrute("mongodb-brute"),
    IpGeolocationMapKml("ip-geolocation-map-kml"),
    WsddDiscover("wsdd-discover"),
    DomconBrute("domcon-brute"),
    InformixBrute("informix-brute"),

    HttpBarracudaDirTraversal("http-barracuda-dir-traversal"),
    BroadcastPppoeDiscover("broadcast-pppoe-discover"),
    HttpServerHeader("http-server-header"),
    SnmpProcesses("snmp-processes"),
    DockerVersion("docker-version"),
    IscsiBrute("iscsi-brute"),
    Skypev2Version("skypev2-version"),
    ImpressRemoteDiscover("impress-remote-discover"),
    TargetsIpv6MulticastEcho("targets-ipv6-multicast-echo"),
    HttpStoredXss("http-stored-xss"),
    XmlrpcMethods("xmlrpc-methods"),
    StuxnetDetect("stuxnet-detect"),
    HadoopNamenodeInfo("hadoop-namenode-info"),
    HttpRfiSpider("http-rfi-spider"),
    RpcapBrute("rpcap-brute"),
    Teamspeak2Version("teamspeak2-version"),
    HttpGitwebProjectsEnum("http-gitweb-projects-enum"),

    NexposeBrute("nexpose-brute"),
    DnsNsid("dns-nsid"),
    SnmpWin32Users("snmp-win32-users"),
    Nbstat("nbstat"),
    NessusBrute("nessus-brute"),
    DicomBrute("dicom-brute"),
    HnapInfo("hnap-info"),
    SslPoodle("ssl-poodle"),
    HttpFeed("http-feed"),
    SmbVulnMs17010("smb-vuln-ms17-010"),
    SnmpWin32Software("snmp-win32-software"),
    NetbusBrute("netbus-brute"),
    MongodbInfo("mongodb-info"),
    Unittest("unittest"),
    HttpGenerator("http-generator"),
    NdmpVersion("ndmp-version"),
    BroadcastOspf2Discover("broadcast-ospf2-discover"),
    DaapGetLibrary("daap-get-library"),
    IrcInfo("irc-info"),
    HttpChrono("http-chrono"),
    DnsIp6ArpaScan("dns-ip6-arpa-scan"),
    Rfc868Time("rfc868-time"),
    HttpDominoEnumPasswords("http-domino-enum-passwords"),
    MetasploitXmlrpcBrute("metasploit-xmlrpc-brute"),
    SmbVulnCve20177494("smb-vuln-cve-2017-7494"),
    RmiDumpregistry("rmi-dumpregistry"),
    SnmpInfo("snmp-info"),
    HttpVulnCve20113192("http-vuln-cve2011-3192"),
    HttpWordpressUsers("http-wordpress-users"),
    NessusXmlrpcBrute("nessus-xmlrpc-brute"),
    Krb5EnumUsers("krb5-enum-users"),
    TargetsSniffer("targets-sniffer"),
    HartipInfo("hartip-info"),
    HttpTplinkDirTraversal("http-tplink-dir-traversal"),
    Sshv1("sshv1"),
    IpHttpsDiscover("ip-https-discover"),
    SmbSystemInfo("smb-system-info"),
    WhoisDomain("whois-domain"),
    KnxGatewayDiscover("knx-gateway-discover"),
    HttpVulnMisfortuneCookie("http-vuln-misfortune-cookie"),
    SmbEnumProcesses("smb-enum-processes"),
    HttpVulnCve20121823("http-vuln-cve2012-1823"),
    MembaseHttpInfo("membase-http-info"),
    HttpAuth("http-auth"),
    DicomPing("dicom-ping"),

    MysqlDumpHashes("mysql-dump-hashes"),
    NfsLs("nfs-ls"),
    HttpAdobeColdfusionApsa1301("http-adobe-coldfusion-apsa1301"),
    HttpVulnCve20143704("http-vuln-cve2014-3704"),
    Ipv6MulticastMldList("ipv6-multicast-mld-list"),
    HttpLs("http-ls"),
    TargetsIpv6Eui64("targets-ipv6-eui64"),
    HttpMcmp("http-mcmp"),
    EapInfo("eap-info"),
    GiopInfo("giop-info"),
    HttpMethodTamper("http-method-tamper"),
    AfpServerinfo("afp-serverinfo"),
    NcpServerinfo("ncp-serverinfo"),
    HttpJsonpDetection("http-jsonp-detection"),
    DnsZeustracker("dns-zeustracker"),
    OracleBruteStealth("oracle-brute-stealth"),
    MetasploitInfo("metasploit-info"),
    MsSqlEmptyPassword("ms-sql-empty-password"),
    AfpShowmount("afp-showmount"),
    Rusers("rusers"),
    SmtpCommands("smtp-commands"),
    BroadcastPcDuo("broadcast-pc-duo"),
    HttpFileuploadExploiter("http-fileupload-exploiter"),
    IpmiCipherZero("ipmi-cipher-zero"),
    EppcEnumProcesses("eppc-enum-processes"),
    HttpWebdavScan("http-webdav-scan"),
    IpGeolocationMapGoogle("ip-geolocation-map-google"),
    Qscan("qscan"),
    HttpDombasedXss("http-dombased-xss"),
    SstpDiscover("sstp-discover"),
    LuEnum("lu-enum"),
    TargetsIpv6Wordlist("targets-ipv6-wordlist"),
    HttpRobtexSharedNs("http-robtex-shared-ns"),
    MqttSubscribe("mqtt-subscribe"),
    OracleBrute("oracle-brute"),
    Finger("finger"),
    HttpBackupFinder("http-backup-finder"),
    UptimeAgentInfo("uptime-agent-info"),
    HttpVulnCve20142126("http-vuln-cve2014-2126"),
    RedisBrute("redis-brute"),
    BroadcastDhcpDiscover("broadcast-dhcp-discover"),
    AfpLs("afp-ls"),
    IrcSaslBrute("irc-sasl-brute"),
    TftpEnum("tftp-enum"),
    HttpVulnCve20148877("http-vuln-cve2014-8877"),
    AfpPathVuln("afp-path-vuln"),
    HttpVlcstreamerLs("http-vlcstreamer-ls"),

    HttpSvnEnum("http-svn-enum"),
    S7Info("s7-info"),
    BackorificeBrute("backorifice-brute"),
    HttpAspnetDebug("http-aspnet-debug"),
    DrdaInfo("drda-info"),
    HttpDate("http-date"),
    SocksBrute("socks-brute"),
    UbiquitiDiscovery("ubiquiti-discovery"),
    HttpVulnCve20102861("http-vuln-cve2010-2861"),
    HttpAvayaIpofficeUsers("http-avaya-ipoffice-users"),
    DnsZoneTransfer("dns-zone-transfer"),
    TsoEnum("tso-enum"),

    HttpVulnCve20113368("http-vuln-cve2011-3368"),
    Quake3MasterGetservers("quake3-master-getservers"),
    SmbSecurityMode("smb-security-mode"),
    HttpIisWebdavVuln("http-iis-webdav-vuln"),
    BroadcastWpadDiscover("broadcast-wpad-discover"),
    TargetsIpv6Map4to6("targets-ipv6-map4to6"),
    MysqlQuery("mysql-query"),
    FingerprintStrings("fingerprint-strings"),
    CouchdbDatabases("couchdb-databases"),
    HadoopDatanodeInfo("hadoop-datanode-info"),
    Omp2Brute("omp2-brute"),
    DpapBrute("dpap-brute"),
    SshBrute("ssh-brute"),
    HttpPut("http-put"),
    OpenlookupInfo("openlookup-info"),
    AjpBrute("ajp-brute"),

    OpenvasOtpBrute("openvas-otp-brute"),
    AfpBrute("afp-brute"),
    RealvncAuthBypass("realvnc-auth-bypass"),

    BroadcastNetbiosMasterBrowser("broadcast-netbios-master-browser"),
    VncBrute("vnc-brute"),
    PathMtu("path-mtu", 0),
    XmppInfo("xmpp-info"),
    LltdDiscovery("lltd-discovery"),
    FlumeMasterInfo("flume-master-info"),
    VncInfo("vnc-info"),
    HostmapRobtex("hostmap-robtex"),
    UrlSnarf("url-snarf"),
    MsSqlConfig("ms-sql-config"),
    OmronInfo("omron-info"),
    RdpVulnMs12020("rdp-vuln-ms12-020"),
    Mrinfo("mrinfo"),
    FtpBounce("ftp-bounce"),
    OracleEnumUsers("oracle-enum-users"),
    HttpOpenRedirect("http-open-redirect"),
    HttpTitle("http-title"),
    CicsEnum("cics-enum"),
    FtpVsftpdBackdoor("ftp-vsftpd-backdoor"),
    NfsStatfs("nfs-statfs"),
    SslDate("ssl-date"),
    HttpAffiliateId("http-affiliate-id"),
    HttpPhpmyadminDirTraversal("http-phpmyadmin-dir-traversal"),
    P2pConficker("p2p-conficker"),
    HttpEnum("http-enum"),
    SmbPrintText("smb-print-text"),
    CicsUserBrute("cics-user-brute"),
    SnifferDetect("sniffer-detect"),
    Resolveall("resolveall"),
    ImapNtlmInfo("imap-ntlm-info"),
    IpGeolocationMapBing("ip-geolocation-map-bing"),
    HttpConfigBackup("http-config-backup"),
    LexmarkConfig("lexmark-config"),
    OracleTnsVersion("oracle-tns-version"),
    DnsNsec3Enum("dns-nsec3-enum"),
    SmtpStrangeport("smtp-strangeport"),
    HttpApacheNegotiation("http-apache-negotiation"),
    BroadcastDnsServiceDiscovery("broadcast-dns-service-discovery"),
    ReverseIndex("reverse-index"),
    RpcapInfo("rpcap-info"),
    HttpApacheServerStatus("http-apache-server-status"),

    SanityCheck(-1),
    DropScanDataTables(-1),
    TruncateScanData(-1), ArpNames(-1);


    private String tag;
    private final Integer priority;

    Provenance(String tag) {
        this();
        this.tag = tag;
    }
    Provenance(String tag, Integer priority) {
        this.priority = priority;
        this.tag = tag;
    }
    Provenance() {
        this.tag = null;
        this.priority = -1;
    }

    Provenance(Integer priority) {
        this.priority = priority;
    }
    public static Provenance fromString(String str) {
        for(Provenance p : Provenance.values()) {
            if(p.name().equalsIgnoreCase(str)) {
                return p;
            }
            if(p.tag != null ) {
                if (p.tag.equalsIgnoreCase(str)) {
                    return p;
                }
            }
        }
        return null;
    }

    public static List<Provenance> getInfrastructure() {
        Provenance[] steps = new Provenance[]{
                NetworkMaps,
                NetworkBlocks,
                IPAddresses,
                Ports,
                OperatingSystems,
                Services,
                DNSConfiguration,
                AliveMachines,
                Systems,
                Repositories,
                Technologies
        };
        return Arrays.asList(steps);
    }

    public static Provenance[] getDetermineFirewallRulesSteps() {
        return new  Provenance[] {
                DetectPacketForgeryByFirewall,
                DetectPacketForgeryByIDS
        };
    }

    public static Provenance[] getPhishing() {
        return new  Provenance[] {
                Email,SMS,Social,MaliciousLinks,MaliciousAttachments,
                SensitiveInformation,SpearPhishing,Phishing,MassAttacks
        };
    }

    public static Provenance[] getScripts() {
        return new  Provenance[] {
                Wappalyzer, HttpRecon,
                WafDetect, WafFingerPrint,AckScan,
                DnsRecon, DnsEnum, WafW00f, WebTech, theHarvester,
                Fierce, LoadBalance, Dmitry, DnsMap, Nikto,
                Sublist3r,WhoIs,LoadBalance,
                Firewalk,AmassEnum,Sherlock,Katana,SynScanBadCheckSum,
                SpiderFoot, Nuclei, Dalfox, AssetFinder, DetectOs,
                DetectTCPServices
        };
    }

    public static List<Provenance> getSafeValues() {
        final List<Provenance> vals = new ArrayList<>();
        vals.addAll(Arrays.asList(values()));
        vals.remove(SanityCheck);
        vals.remove(DropScanDataTables);
        vals.remove(TruncateScanData);
        return vals;
    }

    public Integer getPriority() {
        return priority;
    }

    public String getTag() {
        return tag;
    }
}
