spring.application.name=htf-boot
# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/teto
spring.datasource.username=postgres
spring.datasource.password=R00tyT00ty
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

